# Generated by Django 5.0 on 2023-12-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='description',
        ),
        migrations.AddField(
            model_name='assessments',
            name='AnxietyScore',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='assessments',
            name='IQScore',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='assessments',
            name='PersonalityScore',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
