# Generated by Django 5.0 on 2023-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_description_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='AnxietyScore',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='IQScore',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='PersonalityScore',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
    ]
