# Generated by Django 5.0 on 2023-12-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_yourmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='ResourceHub',
        ),
    ]
