# Generated by Django 5.0 on 2023-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_yourmodel_resourcehub'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('time_8am', models.CharField(blank=True, max_length=255, null=True)),
                ('time_9am', models.CharField(blank=True, max_length=255, null=True)),
                ('time_10am', models.CharField(blank=True, max_length=255, null=True)),
                ('time_11am', models.CharField(blank=True, max_length=255, null=True)),
                ('time_1pm', models.CharField(blank=True, max_length=255, null=True)),
                ('time_2pm', models.CharField(blank=True, max_length=255, null=True)),
                ('time_3pm', models.CharField(blank=True, max_length=255, null=True)),
                ('time_4m', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='IQScore',
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='PersonalityScore',
        ),
    ]
