# Generated by Django 5.0 on 2023-12-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clinicbranches_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicbranches',
            name='username',
        ),
    ]
