# Generated by Django 5.0 on 2023-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_clinicbranches_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
