# Generated by Django 5.0 on 2024-01-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_branch_doctor_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
