# Generated by Django 5.0 on 2024-01-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_doctor_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('branch', models.CharField(max_length=255)),
                ('time_8am_9am', models.BooleanField(default=True)),
                ('time_9am_10am', models.BooleanField(default=True)),
                ('time_10am_11am', models.BooleanField(default=True)),
                ('time_11am_12pm', models.BooleanField(default=True)),
                ('time_1pm_2pm', models.BooleanField(default=True)),
                ('time_2pm_3pm', models.BooleanField(default=True)),
                ('time_4pm_5pm', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
    ]
