# Generated by Django 5.0 on 2024-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_appointment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_3pm_4pm',
            field=models.BooleanField(default=True),
        ),
    ]
