# Generated by Django 5.0 on 2024-01-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
