# Generated by Django 5.0 on 2024-01-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_clients_notes_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
