# Generated by Django 5.0 on 2024-01-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_note_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
