# Generated by Django 5.0 on 2024-01-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='appointment_type',
            field=models.CharField(choices=[('online', 'Online'), ('face_to_face', 'Face to Face')], default='face_to_face', max_length=20),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
