# Generated by Django 5.0 on 2024-01-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_clients_appointment_type_alter_clients_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='status',
        ),
    ]
