# Generated by Django 5.0 on 2024-01-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_clients_age_remove_clients_appointment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='client',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
