# Generated by Django 5.0 on 2024-01-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_clients_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='appointment_time',
            field=models.CharField(max_length=50),
        ),
    ]
