# Generated by Django 5.0 on 2024-01-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_username_assessments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_id',
            new_name='userID',
        ),
    ]
