# Generated by Django 5.0 on 2024-01-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='appointment_type',
        ),
    ]
