# Generated by Django 5.0 on 2024-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_clients_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
