# Generated by Django 5.0 on 2024-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_clients_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicbranches',
            name='location',
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='city_town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicbranches',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
