# Generated by Django 5.0 on 2024-02-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_clients_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
